apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dkron.fullname" . }}-server
  labels:
    {{- include "dkron.serverLabels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  podManagementPolicy: Parallel
{{/*  minReadySeconds: {{ .Values.server.minReadySeconds }}*/}}
  selector:
    matchLabels:
      {{- include "dkron.serverSelectorLabels" . | nindent 6 }}
  serviceName: {{ include "dkron.fullname" . }}
  template:
    metadata:
      annotations:
      {{- with .Values.server.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.image.pullPolicy "Always" }}
        uuid: {{ uuidv4 }}
      {{- end }}
      labels:
        component: server
        {{- include "dkron.serverSelectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dkron.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "dkron" ]
          args:
            - "agent"
            - "--server"
            - "--data-dir=/dkron"
            - "--log-level={{ .Values.server.log.level }}"
            - "--bootstrap-expect={{ include  "dkron.bootstrapExpect" . }}"
            - "--serf-reconnect-timeout=5s"
            - "--raft-multiplier=1"
            - "--retry-join=\"provider=k8s label_selector=\"\"app.kubernetes.io/instance={{ .Release.Name }}\"\" namespace=\"\"{{ .Release.Namespace }}\"\"\""
          volumeMounts:
            - name: "data"
              mountPath: "/dkron"
          ports:
            - name: http
              containerPort: 8080
            - name: serf
              containerPort: 8946
            - name: grpc
              containerPort: 6868
          lifecycle:
            preStop:
              exec:
                command: [ "dkron", "leave" ]
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "dkron.fullname" . }}-envs
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
{{/*          startupProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /v1*/}}
{{/*              port: 8080*/}}
{{/*            initialDelaySeconds: 1*/}}
{{/*            timeoutSeconds: 3*/}}
{{/*            failureThreshold: 5*/}}
{{/*            periodSeconds: 3*/}}
{{/*          livenessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /health*/}}
{{/*              port: 8080*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 30*/}}
{{/*            timeoutSeconds: 3*/}}
{{/*            failureThreshold: 3*/}}
{{/*          readinessProbe:*/}}
{{/*            httpGet:*/}}
{{/*              path: /v1/leader*/}}
{{/*              port: 8080*/}}
{{/*            initialDelaySeconds: 30*/}}
{{/*            periodSeconds: 30*/}}
{{/*            timeoutSeconds: 3*/}}
{{/*            failureThreshold: 3*/}}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.updateStrategy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.server.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.server.persistence.size }}
